---
name: Check for Merge Conflicts
description: Check for Merge Conflicts
author: tikmirumian
branding:
  icon: 'git-pull-request'
  color: 'blue'
inputs:
  repo-token:
    description: The GITHUB_TOKEN secret
    required: true
runs:
  using: node16
  main: action/index.js